apiVersion: v1
kind: Service
metadata:
  labels:
    app: alex
  name: alex
  selfLink: /api/v1/namespaces/default/services/alex
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: alex
  sessionAffinity: None
  type: ClusterIP
